import = [
	#"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 11

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[window]
startup_mode = "Maximized"
decorations = "None"
