vim.loader.enable()

require("vim._core.ui2").enable()

require("config.options")
require("config.keymaps")
require("config.lsp")

require("plugins.mason")
require("plugins.treesitter-manager")
require("plugins.blink")
require("plugins.render-markdown")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.oil")
require("plugins.notify")
require("plugins.noice")
require("plugins.zen-mode")
require("plugins.org-mode")
