export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

source /usr/share/fzf/shell/key-bindings.zsh
source $HOME/.config/zsh/fzf-tab.zsh
source $HOME/.config/zsh/user.zsh
